# Generated by Django 5.1.1 on 2025-07-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="type_reservation",
            field=models.CharField(
                choices=[
                    ("RECLAMATION", "Réclamation"),
                    ("DEMANDE_INFO", "Demande d'information"),
                    ("DEMANDE_BRANCHEMENT", "Demande de branchement"),
                    ("FACTURE", "Problème de facturation"),
                    ("PANNE", "Signalement de panne"),
                    ("AUTRE", "Autre"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
